// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function DeleteArticle(arg1) {
  return window['go']['main']['App']['DeleteArticle'](arg1);
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetNoteByID(arg1) {
  return window['go']['main']['App']['GetNoteByID'](arg1);
}

export function UpdateNoteText(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteText'](arg1, arg2);
}

export function UpdateNoteTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteTitle'](arg1, arg2);
}
