// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote(arg1:main.CreateNoteParams):Promise<main.Note>;

export function DeleteArticle(arg1:number):Promise<void>;

export function GetAllNotes():Promise<Array<main.Note>>;

export function GetNoteByID(arg1:number):Promise<main.Note>;

export function UpdateNoteText(arg1:number,arg2:string):Promise<void>;

export function UpdateNoteTitle(arg1:number,arg2:string):Promise<void>;
